const Hotelitem = [
  {
    id: 1,
    Hotel: ' Vilas Palace',
    Place: 'Agra',
    Type: '*****5 star',
    description: 'The travellers looking for five-star Hotels in Agra can choose from properties like Amar Vilas Palace, Taj Gateway, Hotel Trident, etc.',
    price: 1500,
    image: 'img/agra.jpg',
  },
  {
    id: 2,
    Hotel: 'Hotel Radison',
    Place: 'Jaipur',
    Type: 'Luxury Hotel',
    description: 'The lavish features of Hotel Radisson makes it one of the most sought after hotels in Jaipur.',
    price: 1000,
    image: 'img/radisson.jpg',
  },
  {
    id: 3,
    Hotel: 'Cambay Resort',
    Place: 'Udaipur',
    Type: 'Luxury Hotel',
    description: 'Udaipur also known as City of Lakes is among the jewel cities in Rajasthan..',
    price: 1200,
    image: 'img/HOTEL4.jpg',
  },
  {
    id: 4,
    Hotel: 'Hotel In Leh',
    Place: 'Ladakh',
    Type: ' *****5 start',
    description: 'The region has hotels ranging right from the classic and traditional budget hotels to boutique resorts.',
    price: 2000,
    image: 'img/HOTEL1.jpg',
  },
  {
    id: 5,
    Hotel: 'Mayfair Resort',
    Place: 'Odisha',
    Type: 'Luxury Hotel',
    description: 'It is a place filled with overwhelming beaches and abundant natural beauty making the place ideal for beach .',
    price: 1800,
    image: 'img/HOTEL2.jpg',
  },
  {
    id: 6,
    Hotel: 'Bonhabi Resort',
    Place: 'Kaziranga',
    Type: 'Luxury Hotel',
    description: 'There are many hotels and resorts situated in proximity to the entrance of the Tadoba Tiger reserve.',
    price: 1000,
    image: 'img/HOTEL8.JPG',
  },
  {
    id: 7,
    Hotel: 'Taj Resort',
    Place: 'Utterkhand',
    Type: 'Luxury Hotel',
    description: 'The holy city of Rishikesh, in the base of the Himalayas, and spiritual significance for local Hindus.',
    price: 2000,
    image: 'img/Hotel10.jpeg',
  },
  {
    id: 8,
    Hotel: 'Hotel in Beach',
    Place: ' Goa Beach',
    Type: 'Luxury Hotel',
    description: 'Goa is famous for its picturesque beaches, vibrant nightlife, and Portuguese-influenced architecture.',
    price: 2000,
    image: 'img/hotel11.jpg',
  },
  {
    id: 9,
    Hotel: 'Mount Stay',
    Place: ' Darjeeling',
    Type: 'Luxury Hotel',
    description: 'Nearby attractions include Himalayan Tibet Museum (500 m) and Lloyd Botanical Garden (1 km).',
    price: 2000,
    image: 'img/hotel12.jpg',
  },
  {
    id: 10,
    Hotel: 'Himalayan',
    Place: ' Manali',
    Type: 'Luxury Hotel',
    description: 'The twin hill station positioned in the fascinating north Indian state of Himachal Pradesh.',
    price: 2000,
    image: 'img/hotel13.jpg',
  },

]
export default Hotelitem;